import { DefaultTheme } from 'styled-components/native';

export const theme: DefaultTheme = {
    BAR_STYLE: 'dark-content',
    BAR_BACKGROUND_COLOR: 'transparent',
    BACKGROUND_COLOR: '#faf6ed',
    PRIMARY_COLOR: '#4a4a4a',
    SECONDARY_COLOR: '#636262',
    BORDER_COLOR: '#dfe0e2',
    ALERT_COLOR: '#db1f48',
    LIGHT_COLOR: '#fff',
    TITLE_COLOR: '#4a4a4a',
    PALLETE01_COLOR: '#e5ddc8',
    PALLETE02_COLOR: '#01949a',
    PALLETE03_COLOR: '#004369',
    PALLETE04_COLOR: '#db1f48',
    GRAY_COLOR: '#dfe0e2',
    OVERBACKGROUND_COLOR: '#4a4a4a',
    GREEN_COLOR: '#21B3AF',
    GREEN_COLOR_DARK: '#177472',
    YELLOW_COLOR: '#FFE47E',
    YELLOW_COLOR_DARK: '#BEAC68',
    RED_COLOR: '#FF5757',
    RED_COLOR_DARK: '#DB1F48',
};
